[gcp_credentials]
client_id = "651949606472-f4mrp1lc5f5j3hsigukg13gs5o7k4cng.apps.googleusercontent.com"
client_secret = "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"
scopes = ["https://www.googleapis.com/auth/bigquery"]
